File→folder
rogy-AquaLab/omniboat_robokit pull request #110
Opened 2024-04-04 17:33 UTC by 23-saho

2024-04-05 15:27 UTC, H1rono requested changes
docs/assets以下に画像を置いてください、あと画像の名前をもうちょい考えてください

2024-04-07 01:51 UTC, Chikurin1014 commented
ことばきつい

2024-04-07 02:04 UTC, H1rono commented
ごめんなさい

2024-04-07 03:05 UTC, 23-saho commented
全然きつくないです
遅くなってすみません

2024-04-07 03:49 UTC, H1rono reviewed
プレビューが間延びしちゃってるので、箇条書きの間はもうちょっと空行減らしても良さそうです
記述例↓

```markdown
> 1. hogehoge
>     <img ... >
>
> 2. fugafuga
>     <img ... >
>
> 3. hugahuga
>     <img ... >
>
> #### Mac
> 1. foobar
> 2. fizzbazz
```

2024-04-07 03:49 UTC, H1rono commented on docs/04-environment-setup.md
> +>1. zipをダウンロードすると右上にタブが出てくるのでダウンロードが終わってから"omniboat_robokit_main.zip"のzipファイルににポインタを当ててファイルマークをクリックしてください。
ファイル名のところはコードブロックの方がわかりやすいかも
```suggestion
>1. zipをダウンロードすると右上にタブが出てくるのでダウンロードが終わってから `omniboat_robokit_main.zip` のzipファイルににポインタを当ててファイルマークをクリックしてください。
```

2024-04-07 03:49 UTC, H1rono commented on docs/04-environment-setup.md
> +>    <img alt src="2024-03-31 (6).png" width=250 >
パスが古いままですね...
あと、`alt`の存在と`width`の指定がちょっと怪しいので↓を参考に書き換えてください

https://github.com/rogy-AquaLab/omniboat_robokit/blob/823768041a014ecc79cefd5941b06e0deb8e5f21/docs/04-environment-setup.md?plain=1#L23

他のところも

2024-04-07 03:49 UTC, H1rono commented on docs/04-environment-setup.md
> +>1. ダウンロードフォルダからデスクトップフォルダに移動させてください。
これ、デスクトップじゃなくてドキュメントの方がいいかも(半ば個人的な好み)

2024-04-07 09:17 UTC, H1rono commented on docs/assets/zip_allopen.png
これもしかしてスマホで撮った？
ちょっと気になるのでスクリーンショットにしてほしいです

2024-04-07 09:17 UTC, H1rono commented on docs/assets/zip_document.png
展開先のパスに日本語が含まれているとバグるので、`C:\Users\USERNAME\Documents`に展開している様子にして欲しいです

2024-04-07 09:17 UTC, H1rono commented on docs/04-environment-setup.md
> +>   <img src="assets/zip_explorer.png" sttyle="max-width:300px;" > &emsp; <img src="assets\zip_allopen.png" style="max-width:300px;" >
パスの区切りはバックスラッシュではなくスラッシュで
あと`style`のtypoしてます
```suggestion
>   <img src="assets/zip_explorer.png" style="max-width:300px;" > &emsp; <img src="assets/zip_allopen.png" style="max-width:300px;" >
```

2024-04-07 09:17 UTC, H1rono commented on docs/04-environment-setup.md
> +（またはエクスプローラーのダウンロードフォルダからzipファイルを探してください。）<br>
`<br>`いらないかも？あと行頭に`>`が入ってないの気になってきた
```suggestion
>（またはエクスプローラーのダウンロードフォルダからzipファイルを探してください。）<br>
```

2024-04-07 10:57 UTC, H1rono commented on docs/04-environment-setup.md
> +>   <img src="assets/zip_document.png" style="max-width:300px;" >
`s`抜けちゃってます
```suggestion
>   <img src="assets/zip_documents.png" style="max-width:300px;" >
```

2024-04-07 10:57 UTC, H1rono commented on docs/04-environment-setup.md
他のレビューも対応お願いします

2024-04-07 10:59 UTC, H1rono commented on docs/04-environment-setup.md
> +（またはエクスプローラーのダウンロードフォルダからzipファイルを探してください。）<br>
`<br>`は必要ですね、ただ行頭の`>`が気になる

2024-04-07 11:00 UTC, H1rono commented
あと、画像の上の空行を消すように言ったけどやっぱりあった方がいいかも...?

2024-04-09 05:33 UTC, H1rono approved these changes
👍

2024-04-09 05:33 UTC, merged