add //NOLINT
rogy-AquaLab/omniboat_robokit pull request #131
Opened 2024-04-14 14:51 UTC by Noir-swim

src/schneider_model.cpp:13: [high:error] constructor does not initialize these fields: volume_, adcIn1, adcIn2, volume, servo_1, servo_2, fet_1, fet_2, led1, led2, led3, pc 
このエラーを直そうとしたがclang-tidyの判断が悪そうなので
13行目に//NOLINTを追加しました。

2024-04-14 21:30 UTC, H1rono commented on src/schneider_model.cpp
> +Schneider::Schneider() :  // NOLINT
変更はここだけのはずなのでこれ以外戻してください

2024-04-17 11:26 UTC, H1rono submitted a review, later dismissed

2024-04-17 11:29 UTC, H1rono requested changes
https://github.com/rogy-AquaLab/omniboat_robokit/actions/runs/8721030836/job/23923867604?pr=131

clang-formatが失敗してるので、コメントの場所変える必要があります
`NOLINTBEGIN`と`NOLINTEND`で囲う方針の方がいいかも

2024-04-17 12:00 UTC, H1rono commented on src/schneider_model.cpp
>  }
```suggestion
}
// NOLINTEND(cppcoreguidelines-pro-type-member-init)
```

2024-04-20 15:05 UTC, Noir-swim commented on src/schneider_model.cpp
>  }
気づくのがおそくなってしまいすみません..
40行目にコメントを移動してプッシュしました。

2024-04-20 15:53 UTC, H1rono commented
@Noir-swim ところでローカルのアカウント大丈夫でしょうか？ @Noir-milktea 名義でコミットしてますが

2024-04-20 15:54 UTC, H1rono commented
`git config --global user.name`と`git config --global user.email`確認してください
リポジトリごとで分ける場合は`git config user.name`と`git config user.email`です

2024-04-20 15:55 UTC, H1rono approved these changes

2024-04-21 10:01 UTC, Noir-swim commented
昨日、大学の方でgithubをいじっていてGitHub desktopをインストールして別アカウントを紐づけてしまったことが原因です。。
Noir-swimの名義に直しました。
コマンドプロンプトでユーザー名、メールアドレスを確認したところ、ユーザー名、メールアドレス共にNoir-swimの名義に戻っております。
お騒がせしました....💦

2024-04-21 18:18 UTC, merged