add a section for cuircuit developers
rogy-AquaLab/omniboat_robokit pull request #137
Opened 2024-04-17 00:28 UTC by Chikurin1014

#82

2024-04-17 00:32 UTC, Chikurin1014 commented
Warning表記何もわかってないので教えてください

2024-04-17 02:06 UTC, H1rono requested changes
SUMMARY.mdの方もよしなに書いて欲しいです

2024-04-17 02:06 UTC, H1rono commented on docs/for-developers/dev-circuit.md
> +ハウジングのツメ ≠ コンタクトのツメ
この記法ないので、↓に従ってください
https://rust-lang.github.io/mdBook/format/mdbook.html#classwarning

2024-04-17 02:06 UTC, H1rono commented on docs/for-developers/dev-circuit.md
> +# 開発者向けセクション 回路
SUMMARYの方で`開発者向け`というのは示してるから、二重で書く必要はないかな

2024-04-17 02:06 UTC, H1rono commented on docs/for-developers/dev-circuit.md
> +  - 向きがそろっていればなんでもよい。
50行目とインデント幅が違う
4マスのインデントが好みなのでそうしてください

2024-04-17 02:44 UTC, Chikurin1014 commented
@H1rono 再確認お願いします

2024-04-17 02:48 UTC, Chikurin1014 commented
@rein0925 
GoogleDriveで共有されている納品表の緑色LEDのリンクが黄色LEDになっていたのと、秋月電子のリンクがすべて古いものになっていた(まだリダイレクトが効いているので、開くことはできる)ので、こちらのドキュメントで修正を加えています。(Driveの方は直してません)

2024-04-17 09:49 UTC, H1rono commented on docs/for-developers/dev-circuit.md
> +<div class = Warning>
そんな書き方見たことないけど

2024-04-18 02:02 UTC, Chikurin1014 commented
お願いします

2024-04-18 04:57 UTC, H1rono approved these changes

2024-04-18 04:57 UTC, merged