deal with magic numbers in schneider_model.cpp
rogy-AquaLab/omniboat_robokit pull request #138
Opened 2024-04-17 01:39 UTC by Chikurin1014

solved errors on clang-tidy:
- `src/schneider_model.cpp:80: [high:error] 0.4F is a magic number; consider replacing it with a named constant  [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers,-warnings-as-errors]`
- `src/schneider_model.cpp:80: [high:error] 0.7F is a magic number; consider replacing it with a named constant  [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers,-warnings-as-errors]`
- `src/schneider_model.cpp:142: [high:error] 1e-3 is a magic number; consider replacing it with a named constant  [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers,-warnings-as-errors]`
- `src/schneider_model.cpp:169: [high:error] 0.4F is a magic number; consider replacing it with a named constant  [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers,-warnings-as-errors]`
- `src/schneider_model.cpp:172: [high:error] 0.4F is a magic number; consider replacing it with a named constant  [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers,-warnings-as-errors]`

2024-04-17 01:41 UTC, Chikurin1014 commented
後ろ2つ、何故か@H1ronoが共有してる中に存在しないエラーなんだよね

2024-04-17 01:47 UTC, rein0925 commented
>   後ろ2つ、何故か@H1ronoが共有してる中に存在しないエラーなんだよね

そのエラーはthisポインタの明示をしたら新たに生じたエラーだったはずです

2024-04-17 02:07 UTC, H1rono commented
僕の更新ミス

2024-04-17 11:43 UTC, H1rono requested changes

2024-04-17 11:43 UTC, H1rono commented on include/schneider_model.hpp
> +constexpr float joyEffectiveRangeMin = 0.4F;
`effectiveRange`は流石に長すぎるので`threshold`の方がいい
`volume`に関しては既にあるのでしょうがないとして、`diff`も

2024-04-17 11:43 UTC, H1rono commented on include/schneider_model.hpp
> +constexpr std::array<float, 2> volumeEffectiveRange = {0.4F, 0.7F};
列ではなく組なので`pair`かなあ
あと、ここだけ見ると「この範囲内に`volume`があったらなんか起こるのかな」と思っちゃいそうなので、`ineffective`の方がいいかも

2024-04-17 11:43 UTC, H1rono commented on src/schneider_model.cpp
> +        = volumeEffectiveRange[0] < volume_ && volume_ < volumeEffectiveRange[1];
これは`volumeIneffective`の条件では？ここでやりたいのは「ツマミが十分に回されていたら回転する」という動作なので

2024-04-17 20:15 UTC, H1rono commented
#56

2024-04-18 02:03 UTC, Chikurin1014 commented
お願いします

2024-04-18 05:19 UTC, H1rono approved these changes

2024-04-18 05:19 UTC, merged