remove args of joy_read
rogy-AquaLab/omniboat_robokit pull request #162
Opened 2024-04-26 07:30 UTC by Chikurin1014

2024-04-26 07:56 UTC, H1rono commented on src/schneider_model.cpp
> +    x_d = this->joy_read();
```suggestion
    this->x_d = this->joy_read();

```

2024-04-26 07:56 UTC, H1rono commented on include/schneider_model.hpp
> +     * @return std::array<float, 3> index0: x, index1: y, index2: omega
`omega`が何かこれだけじゃわからんです

2024-04-26 10:23 UTC, H1rono commented
一回mainブランチマージしてね

2024-04-27 02:55 UTC, Chikurin1014 commented on include/schneider_model.hpp
> +     * @return std::array<float, 3> index0: x, index1: y, index2: omega
実は僕自身意味が分かってない

2024-04-27 02:55 UTC, Chikurin1014 commented on include/schneider_model.hpp
> +     * @return std::array<float, 3> index0: x, index1: y, index2: omega
x_dに代入される値だから、xと次元は同じはず

2024-04-27 03:01 UTC, Chikurin1014 commented on include/schneider_model.hpp
> +     * @return std::array<float, 3> index0: x, index1: y, index2: omega
rotationにもどしました

2024-04-27 09:50 UTC, H1rono requested changes

2024-04-27 09:50 UTC, H1rono commented on include/schneider_model.hpp
> +     * @return std::array<float, 3> index0: x, index1: y, index2: omega
戻されてるように見えないけど...

2024-04-27 09:50 UTC, H1rono commented on src/schneider_model.cpp
> +    return {dest_x, dest_y, dest_omega};
ここも`omega`

2024-04-27 10:04 UTC, Chikurin1014 commented on src/schneider_model.cpp
> +    return {dest_x, dest_y, dest_omega};
pushし忘れたかも。後で確認します

2024-04-28 10:49 UTC, H1rono approved these changes

2024-04-28 10:49 UTC, H1rono commented
#56

2024-04-28 10:49 UTC, merged