deleted 'BufferedSerial pc;'
rogy-AquaLab/omniboat_robokit pull request #171
Opened 2024-05-01 06:52 UTC by Noir-swim

https://github.com/rogy-AquaLab/omniboat_robokit/issues/166

2024-05-01 12:17 UTC, H1rono requested changes
ビルドできてないので、何が良くないか確認して直してください
https://github.com/rogy-AquaLab/omniboat_robokit/actions/runs/8906441209/job/24458598746#step:5:1

2024-05-02 14:43 UTC, Noir-swim commented
src/schneider_model.cpp: In constructor 'omniboat::Schneider::Schneider()':
src/schneider_model.cpp:29:5: error: class 'omniboat::Schneider' does not have any field named 'pc'
   29 |     pc(USBTX, USBRX) {
      |     ^~
*** [.pio/build/nucleo_f303k8/src/schneider_model.o] Error 1
lib/MPU6050/MPU6050.cpp: In member function 'void MPU6050::setGyroRange(char)':
lib/MPU6050/MPU6050.cpp:156:17: warning: suggest parentheses around '+' inside '<<' [-Wparentheses]
  156 |     temp = temp + range << 3;
      |            ~~~~~^~~~~~~
========================= [FAILED] Took 167.12 seconds =========================

このエラーが出ていたのでcppファイルのpcが含まれている箇所を消せばいいと考えているのですがあってますか？？
探したところ、該当箇所はこの部分で

    pc(USBTX, USBRX) {
    led(1);
    led(2);
    led(3);
    printf("start up\n");

    servo_1.period_ms(20);
    servo_2.period_ms(20);
}　

pc(USBTX, USBRX)が｛｝でくくっているので、｝まで消せばいいと思っているのですが、ledの変数まで消してはダメな気がします。。どうすればいいでしょうか？
ちなみに消してみたらエラーが出たので間違っている気がします。。
そもそも
BufferedSerial pc　
を別の変数にすればよかったのでしょうか.......?

2024-05-02 14:49 UTC, Noir-swim commented
![deleted 'BufferedSerial pc;' #171](https://github.com/rogy-AquaLab/omniboat_robokit/assets/145688154/91817d29-d106-42de-b9d5-35ffe0204bb9)
今このようになっています

2024-05-02 22:42 UTC, H1rono commented
はい、そこでは「コンストラクタのメンバ変数初期化子リスト」という構文が使われています
それを踏まえて考えてみてください
https://zenn.dev/melos/articles/7b7fbc5fd41270

2024-05-04 14:23 UTC, Noir-swim commented
もしかしてこれであってますか？？
リンクで記載してあったの構造のように
pcのループを消して、｛｝を加えてみたらエラーが消えました。
![pc()消し問題](https://github.com/rogy-AquaLab/omniboat_robokit/assets/145688154/314799d3-bbb6-4e3c-9394-d1dfce831e8f)
間違っていましたらヒントを教えていただきたいです。。。。

2024-05-04 14:27 UTC, Noir-swim commented
とりあえずプッシュしてみます。

2024-05-04 14:42 UTC, H1rono requested changes

2024-05-04 14:42 UTC, H1rono commented on src/schneider_model.cpp
> -    servo_2.period_ms(20);
中カッコの中はそのままがいいです、`pc`と関係がない部分なので

2024-05-04 14:47 UTC, Noir-swim commented on src/schneider_model.cpp
> -    servo_2.period_ms(20);
中かっこの中身を `,`の群につなげばよい感じでしょうか？

2024-05-04 14:52 UTC, Noir-swim commented on src/schneider_model.cpp
> -    servo_2.period_ms(20);
![image](https://github.com/rogy-AquaLab/omniboat_robokit/assets/145688154/2f945770-23be-4855-b75a-e4345b979efa)

2024-05-04 21:58 UTC, H1rono commented on src/schneider_model.cpp
> -    servo_2.period_ms(20);
合ってます

2024-05-08 10:41 UTC, merged