ヘッダーファイル
rogy-AquaLab/omniboat_robokit pull request #199
Opened 2024-06-01 07:01 UTC by 23-yoshikawa

2024-06-01 07:04 UTC, 23-yoshikawa commented
.cppファイルのほうで
初期化の関数でエラーが出てしまったのですがどうすればよいかわかりませんでした。
もともとあったinputmodulesの初期化を関数にしようと思ったのですが、だめでした

2024-06-01 10:07 UTC, H1rono commented
そもそもこのissueでやりたいのは、「ピン番号とセンサー・アクチュエーターとの対応関係を明示する」ということです。つまり、以下のようなリファクタリングを入れたいです。

```cpp
// before
InputModules input_modules({A4, A5}, A6, {D4, D5}), output_modules({PB_4, PA_11}, {PA_9, PA_10});

// after
InputModules input_modules = InputModules::builder()
    .joy_pins(A4, A5)
    .volume_pin(A6)
    .mpu_sda_pin(D4)
    .mpu_scl_pin(D5)
    .build();
```

ここまで書いたものは`builder()`から`mpu_scl_pin()`までの実装(怪しいけど)なので、あとは`build()`だけです

```cpp
class Builder {
    ...
    auto build() -> InputModules;
};
```

2024-06-01 10:12 UTC, H1rono commented on include/device/input.hpp
> +        auto mpu_pins(const PinName& pin) -> Builder&;
MPU6050のピン設定はSDA, SCLの2ピンなので`PinName`の値を2つ受け取る必要があります。これはjoyの方も同様です

2024-06-01 10:12 UTC, H1rono commented on src/device/input.cpp
> +*/
これ消しちゃっていいです

2024-06-01 10:12 UTC, H1rono commented on include/device/input.hpp
> +        auto mpu_pins(const PinName& pin) -> Builder&;
で、この2つも区別しづらいので別々に受け取りたいですね

```cpp
auto joy_x_pin(...
auto joy_y_pin(...
auto mpu_sda_pin(...
auto mpu_scl_pin(...
```

2024-06-05 10:19 UTC, H1rono reviewed
かなり良くなってきてる！`Machine`のコンストラクタを変える必要があるので、そこもお願いします

before:

https://github.com/rogy-AquaLab/omniboat_robokit/blob/46c1b3c106126ec64cb2e368ba16c74bd0caca5a/src/machine.cpp#L29

after:

```cpp
input_modules(InputModules::builder()....), ...
```

2024-06-05 10:19 UTC, H1rono commented on include/device/input.hpp
> +        auto mpu_pins(const std::pair<PinName, PinName>& pins) -> Builder&;
pairのfirst, secondがそれぞれ何を意味しているのか明示した版も欲しいです

```cpp
auto joy_x_pin(const PinName& pin) -> Builder&; // joy_pins.first
auto joy_y_pin(const PinName& pin) -> Builder&; // joy_pins.second
auto mpu_sda_pin(const PinName& pin) -> Builder&; // mpu_pins.first
auto mpu_scl_pin(const PinName& pin) -> Builder&; // mpu_pins.second
```

2024-06-05 10:19 UTC, H1rono commented on src/device/input.cpp
> +*/
消してね

2025-03-20 23:48 UTC, H1rono commented
@23-saho checkが失敗してるので、一度ログを確認して直せそうか試して欲しいです

checkの確認は、このPull Request内の`Checks`タブからできます

2025-03-21 01:45 UTC, 23-saho commented
すみません
昨日手元の環境でbuildすることを考えていなかったせいで無駄にpushしてました…

2025-03-21 01:46 UTC, 23-saho commented
`class MPU6050`の使ってる`class I2C`、が継承してる`class NonCopyable`がコピーコンストラクタを削除してるため
`machine.cpp`で`input_modules = InputModules::Builder().～;`ができないのが原因のようです。
どこで消されてるのかわからなかったのですが`MPU6050`がムーブもできないとエラーはかれました。

2025-03-21 01:47 UTC, 23-saho commented
@H1rono 
`class MPU6050`の使ってる`class I2C`、が継承してる`class NonCopyable`がコピーコンストラクタを削除してるため
`machine.cpp`で`input_modules = InputModules::Builder().~;`ができないのが原因のようです。
どこで消されてるのかわからなかったのですがMPU6050がムーブもできないとエラーはかれました。

2025-03-21 03:16 UTC, H1rono reviewed
多分こう変えたら通るはずです

ref: [C++　コンストラクタの後ろにコロンつけてるやつの話　～初期化子リスト～ - はかせのラボ](https://hakase0274.hatenablog.com/entry/2019/09/28/200000), [C++入門者に贈るclass入門とclass/structキーワードの使い分け #C++11 - Qiita](https://qiita.com/yumetodo/items/b0ff58617f2733d4ffa1)

Checkを手元で確認するのは環境構築が必要なため、pushしてトライ&エラーを繰り返しても大丈夫です

2025-03-21 03:16 UTC, H1rono commented on src/machine.cpp
> +        .build());
`input_modules`の初期化を初期化子リストの中でやるといいです。↓みたいな

```cpp
Machine::Machine() :
    input_modules(device::InputModules::builder()....build()),
    output_modules(...), service()
{
    ...
}
```

2025-03-22 02:01 UTC, H1rono commented on src/machine.cpp
> +        .build());
ごめん、`input_modules(std::move(device::InputModules::builder()...))`っぽいです

2025-03-22 03:56 UTC, 23-saho commented
コンストラクタでエラーはかれるのですがどうすればいいのかわからないです…
`InputModules`を関数に代入するのが無理なら`Builder`を渡せないかなと思ったのですが無理でした

2025-03-22 11:00 UTC, H1rono commented on src/machine.cpp
> +        .build());
> ごめん、`input_modules(std::move(device::InputModules::builder()...))`っぽいです

これ初期化子リストの中でやってみましたか？

2025-03-22 11:27 UTC, 23-saho commented on src/machine.cpp
> +        .build());
やってみたのですが同じようにエラー出ました

2025-03-23 10:54 UTC, 23-saho commented
@H1rono 
Builderクラスのコンストラクタ等のdefault/deleteを明示するコードは書いた方がいいですか？

2025-03-24 01:55 UTC, H1rono reviewed
もうちょい！

> Builderクラスのコンストラクタ等のdefault/deleteを明示するコードは書いた方がいいですか？

そうですね、コピーコンストラクタとコピー代入をdeleteして他はdefaultにしてください

2025-03-24 01:55 UTC, H1rono commented on include/device/input.hpp
> +        PinName _mpu_scl_pin;
ここのフィールドはprivateにしたいですね...

`Builder`内から`InputModules`のprivateフィールドにアクセスできるはずなので、こう書けるかも？

```cpp
auto device::InputModules::Builder::build() -> device::InputModules {
    return device::InputModules{
        std::make_pair(mbed::AnalogIn(), mbed::AnalogIn()), // joi
        mbed::AnalogIn(), // volume
        std::make_unique(...), // MPU6050
    };
}
```

これができたら`InputModules`のコンストラクタ`InputModules(Builder*)`が必要なくなるはずです

2025-03-26 05:14 UTC, 23-saho commented
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/easily-swappable-parameters.html
このclangtidyの解決策がstructを使う等らしいのですが、
今回実際のピンの入力は`joy_x_pin()`などで行うので無視していいですか

2025-03-26 06:57 UTC, 23-saho commented on include/device/input.hpp
> +        joy(joy), volume(volume), mpu(std::move(mpu)) {}
すみません１つ前のコメントしてもらったbuild()の書き方が分かっていないようです
InputModulesにコンストラクタが必要だと思ったのですが違うかんじですか

引数と代入先のメンバ変数の名前が同じになってしまっているのがよくないですか

2025-03-26 08:02 UTC, H1rono commented on include/device/input.hpp
> +        joy(joy), volume(volume), mpu(std::move(mpu)) {}
ごめん、書いてみたけど必要っぽいです

<details>
<div>

```cpp
class A {
private:
    int _value;

    A(int value) : _value(value) {}

public:
    class Builder {
    private:
        int _value;

    public:
        Builder();
        auto value(int value) -> Builder&;
        auto build() -> A;
    };

    static auto builder() -> Builder;

    auto value() -> int {
        return _value;
    }
};

A::Builder::Builder() : _value(0) {}

auto A::Builder::value(int value) -> Builder& {
    _value = value;
    return *this;
}

auto A::Builder::build() -> A {
    return A{_value};
}

auto A::builder() -> A::Builder {
    return A::Builder();
}
```

</div>
</details>

> InputModulesにコンストラクタが必要だと思ったのですが違うかんじですか

あってました :bow:

> 引数と代入先のメンバ変数の名前が同じになってしまっているのがよくないですか

問題ないです

> 今回実際のピンの入力は`joy_x_pin()`などで行うので無視していいですか

いいと思います。問題のコンストラクタをこのように囲ってあげてください

```cpp
// NOLINTBEGIN(bugprone-easily-swappable-parameters)
InputModules(...): ... {}
// NOLINTEND(bugprone-easily-swappable-parameters)
```

2025-03-26 13:40 UTC, H1rono requested changes
あとここだけ

2025-03-26 13:40 UTC, H1rono commented on include/device/input.hpp
> +        joy(joy), volume(volume), mpu(std::move(mpu)) {}
こっちの方がスッキリしてる気がする　直さなくてもいいです

```suggestion
    InputModules(
        std::pair<mbed::AnalogIn, mbed::AnalogIn> joy, mbed::AnalogIn volume,
        std::unique_ptr<MPU6050>&& mpu) :
        joy(joy), volume(volume), mpu(mpu) {}
```

2025-03-26 13:40 UTC, H1rono commented on include/device/input.hpp
> +        auto mpu_scl_pin(const PinName& pin) -> Builder&;  // mpu_pins.second
コメントが紛らわしいので消してください

```suggestion
        auto mpu_sda_pin(const PinName& pin) -> Builder&;
        auto mpu_scl_pin(const PinName& pin) -> Builder&;
```

2025-03-26 13:40 UTC, H1rono commented on src/device/input.cpp
> +}
なんか長いな...

```suggestion
auto device::InputModules::Builder::build() -> InputModules {
    const mbed::AnalogIn joy_x(this->_joy_x_pin);
    const mbed::AnalogIn joy_y(this->_joy_y_pin);
    const mbed::AnalogIn volume(this->_volume_pin);
    const auto mpu = std::make_unique<MPU6050>(this->_mpu_sda_pin, this->_mpu_scl_pin);
    return InputModules{std::make_pair(joy_x, joy_y), volume, mpu};
}
```

`const`はなくてもまあいいんだけど、可能であればつけておきたいです。あと`mpu`を渡すところに`std::move`つけないといけないかもです。

2025-03-28 05:40 UTC, 23-saho commented on src/device/input.cpp
> +    auto mpu = std::make_unique<MPU6050>(this->_mpu_sda_pin,this->_mpu_scl_pin);
unique_ptrはconstにできないようで、
その他だけconstにしたらclang-tidyで[readability-convert-member-functions-to-static]が出てstaticに直すように言われたのでconst外してしまいました

2025-03-28 06:05 UTC, H1rono approved these changes
LGTM 👍 
マージお願いします

2025-03-29 04:43 UTC, merged